### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by mansona** [manuelmitasch/ember-inflector-node-shim#1]
Hey there, just wondering if there was a reason why you are not publishing this to NPM?

**Comment by manuelmitasch** [comment]
Last time I spoke with @stefanpenner we discussed to make the [original repo ember-inflector](https://github.com/stefanpenner/ember-inflector) consumeable via node/npm. Since then it was transformed into a Ember CLI plugin. I guess in theory it should be possible to consume the ES6 modules from there, but I never tried it with node.

I would rather not publish a shim project to npm, but create a way to consume the original repo.
That said, I'm too busy to contribute it in the near future.

**Comment by stefanpenner** [comment]
> I would rather not publish a shim project to npm, but create a way to consume the original repo.
> That said, I'm too busy to contribute it in the near future.

I suspect the first step is -> https://github.com/ember-cli/ember-resolver/issues/79

just need someone to push it forward.

**Comment by manuelmitasch** [comment]
I no speak good Ruby ;)

**Comment by stefanpenner** [comment]
> I no speak good Ruby ;)

excellent, the first step is merely removing the ruby :package: 

@chadhietala do you have a fork of resolver that works via npm? I suspect we should coordinate here.

**Comment by chadhietala** [comment]
@stefanpenner No, copypasta job into the ember repo. Since it was being resolved at `ember/resolver`.

**Comment by stefanpenner** [comment]
> @stefanpenner No, copypasta job into the ember repo. Since it was being resolved at ember/resolver.

ah makes sense. Likely a good idea actually moving forward though. Since the two are tightly coupled.
